class CheckoutStepTwoLocators:
    CART_LIST = 'div[data-test="cart-list"]'
    INVENTORY_ITEM = 'div[data-test="inventory-item"]'
    INVENTORY_ITEM_NAME = 'div[data-test="inventory-item-name"]'
    INVENTORY_ITEM_DESC = 'div[data-test="inventory-item-desc"]'
    INVENTORY_ITEM_PRICE = 'div[data-test="inventory-item-price"]'
    SUBTOTAL_PRICE = 'div[data-test="subtotal-label"]'
    TAX_PRICE = 'div[data-test="tax-label"]'
    TOTAL_PRICE = 'div[data-test="total-label"]'
    FINISH_BTN = 'button[data-test="finish"]'
    CANCeL_BTN = 'button[data-test="cancel"]'